apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: order-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: anton230230/notification-service:latest
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/orders_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: user
        - name: SPRING_DATASOURCE_PASSWORD
          value: pass
        - name: SERVER_PORT
          value: "8080"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: order-processing
spec:
  selector:
    app: notification-service
  ports:
  - port: 8080
    targetPort: 8080